# Generated by Django 4.1b1 on 2022-07-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_bookedday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
