# Generated by Django 4.1b1 on 2022-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_alter_room_amenities_alter_room_facilities_and_more"),
        ("lists", "0002_alter_list_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="lists", to="rooms.room"
            ),
        ),
    ]
